Update Lean_LEDE_HC5962_PLUS.yml

diff --git a/.github/workflows/Lean_LEDE_HC5962_PLUS.yml b/.github/workflows/Lean_LEDE_HC5962_PLUS.yml
--- a/.github/workflows/Lean_LEDE_HC5962_PLUS.yml
+++ b/.github/workflows/Lean_LEDE_HC5962_PLUS.yml
@@ -102,17 +102,41 @@ jobs:
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: Compile the firmware
-      id: compile
-      run: |
-        cd openwrt
-        echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
-        echo "::set-output name=status::success"
-        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
-        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-
+    # - name: Compile the firmware
+      # id: compile
+      # run: |
+        # cd openwrt
+        # echo -e "$(nproc) thread compile"
+        # make -j$(nproc) || make -j1 || make -j1 V=s
+        # echo "::set-output name=status::success"
+        # grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+        # [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+        # echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+    - name: Compile the firmware  
+      id: compile  
+      run: |  
+       cd openwrt  
+        # Backup old logs  
+        if [ -f logs/old.log ]; then  
+       mv logs/old.log logs/old_$(date +"%Y%m%d%H%M").log  
+       fi  
+        # Compile the firmware  
+       echo -e "$(nproc) thread compile"  
+       make clean && make -j$(nproc) V=s || true  
+       STATUS=$?  
+       if [ $STATUS -ne 0 ]; then  
+       make -j1 V=s || true  
+       STATUS=$?  
+       fi  
+       if [ $STATUS -ne 0 ]; then  
+       echo "Compilation failed"  
+       exit 1  
+       fi  
+       echo "::set-output name=status::success"  
+        # Save device name and file date  
+       grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME  
+       [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV  
+       echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
     - name: Check space usage
       if: (!cancelled())
       run: df -hT
